// GENERATED FILE - DO NOT EDIT MANUALLY
// This file is auto-generated by flutter gen-l10n.
// Run: flutter gen-l10n to regenerate.
//
// To configure, add to pubspec.yaml:
//   flutter:
//     generate: true
//
// And create l10n.yaml in project root with:
//   arb-dir: lib/shared/l10n
//   template-arb-file: app_en.arb
//   output-localization-file: app_localizations.dart

// TODO: Run `flutter gen-l10n` to generate this file automatically.
// Placeholder until generation:

import 'package:flutter/widgets.dart';

abstract class AppLocalizations {
  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  String get appName;
  String get login;
  String get register;
  String get email;
  String get password;
  String get forgotPassword;
  String get logout;
  String get settings;
  String get profile;
  String get notifications;
  String get home;
  String get retry;
  String get cancel;
  String get confirm;
  String get save;
  String get delete;
  String get edit;
  String get search;
  String get noResults;
  String get loading;
  String get error;
  String get success;
  String get networkError;
  String get unknownError;
  String get welcomeBack;
  String get createAccount;
}
